# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: s3-terraform-lambda

Globals:
  Function:
    Timeout: 60

Resources:
  GlobalDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GlobalDependenciesLayer
      ContentUri: layers/common-dependencies
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs16.x

  GreeterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/greeter.handler
      CodeUri: functions/src/dist
      Runtime: nodejs16.x
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/greeter'
            Method: POST

  S3ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/index.handler
      CodeUri: functions/src/dist
      Layers:
        - !Ref GlobalDependenciesLayer
      Runtime: nodejs16.x
      Events:
        FileUpload:
          Type: S3
          Properties:
            Events: s3:ObjectCreated:*